cloud:
  # GCP, AWS, Azure
  type: "AWS"
  ## OIDC value for the cloud provider for query engine access with Cloud Resources   
  # GCP: Service account email with GCS read access 
  # AWS: IAM role ARN with s3 and/or glue read access
  # Azure:  Client ID of User assigned Managed Identity
  oidc_value: "arn:aws:iam::12345678:role/s3-glue-access-role"
  ## Cross Account user for kubernetes RBAC access to deploy and manage query engine
  # GCP: 
  # - Service account email with GKE viewer access
  # - Service account ID with GKE viewer access
  # AWS:
  # - IAM role ARN with EKS viewer access
  # Azure:
  # - Client ID of Service Principal App with AKS viewer access
  control_plane_user:
    - "arn:aws:iam::12345678:role/eks-viewer-role"
  # - "115022675482241385559"
  # - "dev-e6-helm-op-whyezopu@e6data-analytics.iam.gserviceaccount.com"
  # - "arn:aws:iam::115022675482:role/dev-e6-helm-op-whyezopu"
  # - "e6-helm-op-whyezopu"

karpenter:
  nodepool: "e6data-nodepool"
  ## Name of the karpenter nodepool
  nodeclass: "e6data-nodeclass"
  ## Name of the karpenter nodeclass

# Extra manifests to deploy as an array
extraManifests: []
  # - apiVersion: v1
  #   kind: ConfigMap
  #   metadata:
  #   labels:
  #     name: Platform-operator-extra
  #   data:
  #     extra-data: "value"

