---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ include "e6data.name" . }}
  {{ include "e6data.namespace" . }}
  labels:
    {{- include "e6data.common.labels" . | nindent 4 }}
    {{- include "e6data.serviceaccount.labels" . | nindent 4 }}
  annotations:
    {{- include "e6data.serviceaccount.oidc_key" . | nindent 4 }}: {{ .Values.cloud.oidc_value | quote }}
    {{- include "e6data.serviceaccount.annotations" . | nindent 4 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: e6data-agent
  labels:
    {{- include "e6data.common.labels" . | nindent 4 }}
  {{ include "e6data.namespace" . }}

---
{{- if eq .Values.cloud.type "AZURE" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter-token-update
  namespace: kube-system
  labels:
    {{- include "e6data.common.labels" . | nindent 4 }}
{{- end }}