{{- if ne .Values.ingress.controller "alb" -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "e6data.connectivity.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "e6data.connectivity.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class_name }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
          {{- end }}  
            backend:
              service:
                name: {{ include "e6data.connectivity.fullname" $ }}-service
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
{{- end }}                  
